### ISSUE TITLE
v2 beta punch list

### ISSUE THREAD

**Issue by patrick-rodgers** [pnp/pnpjs#892]
This issue will track the remaining items for the v2 beta release. If you have other items you are not sure will be addressed please comment here, but understand we are not looking to take on major new features before the beta. If you have ideas for larger changes you think would be beneficial please open a new issue as normal and we can consider it for future releases. Thanks!

## TODO for beta
>This list will be updated as we move forward, potentially adding or removing tasks.
- [x] Figure out how to publish docs (rather how to publish along side current docs)
- [x] Update mkdocs index file
- [x] New articles for invokable, selective imports, create your own webpack/rollup package (compare sizes?)
- [x] Final Testing in SPFx (not like last ever, just make sure imports etc work as expected)
- [x] Complete remaining sub modules
  - [x]  related items
  - [x]  security
  - [x]  files
  - [ ]  ~~profiles~~
  - [ ]  ~~navigation~~
  - [ ]  ~~social? docs only?~~
- [x] Ensuring packages are built as expected
- [x] Remove src folder and promote all files up one level to enable cleaner import statements.

## Help Testing the beta
Once the first beta is released we ask that folks try it out in two ways: new projects (SPFx focused, Node, or other) and upgrading existing projects. We are looking for feedback in three main areas:

- **Is something broke?**: please report it as an issue in the list and note that it is for the v2 beta. If you would like we will absolutely welcome PRs to help fix things - but either way please do log the issue so we can have a look.
- **How are the docs?**: Do you see missing or unclear documentation? Did we spell things wrong (liklely)? Please let us know by logging an issue and indicating it is for v2.
- **How is the [transition guide](https://github.com/pnp/pnpjs/blob/dev-v2/docs/transition-guide.md)?**: As you are migrating to v2 from v1 how is the guide? What information is missing? We can't anticipate everything folks are doing, so please let us know or submit an update if you hit a snag while migrating. We want to get the guide as clear as possible, and I am sure there are gaps. Please log an issue and if you have a few minutes a PR to help us out would be great! Thanks!

Thanks to everyone for all the help so far, almost there!

**Comment by patrick-rodgers** [comment]
Closing this, we are good enough to launch the beta at this point. Will now move tasks to #893.
