### ISSUE TITLE
v2 Release Punch List

### ISSUE THREAD

**Issue by patrick-rodgers** [pnp/pnpjs#893]
A placeholder issue to track things we want to do before the release but aren't absolutely required for the initial beta.

## TODO
> We'll update this as we go
- [x] Improve security docs
- [x] Clean up all the old files/folders within the packages directory
- [x] Fix sp/items docs
- [x] Close out project tasks
- [x] Ensure attribution in authors file for all v2 changes
- [x] Update issue templates using new choose a template feature in GitHub
- [x] Complete remaining sub modules docs and tests
  - [X]  profiles
  - [X]  navigation
  - [X] files
  - [x]  social? docs only?
- [x] Figure out branching strategy inside pnpjs repo
- [x] Setup PnPjs package to be a bundle of all the other packages
- [x] Release 2.0.0 version of polyfill package
- [x] Update readme.md in root for v2
- [x] Improve typings and typed update param where possible
- [x] Ensure tagging for all methods
